---
# defaults file for chronos
openssl_self_signed:
 - { name : "{{ ansible_hostname }}" }
generate_random_pass: "true"
chronos_key_password: "password"
chronos_pkcs_password: "password"
chronos_jks_password: "password"
chronos_username: "admin"
chronos_password: "secr3t"
chronos_version: 'latest'
chronos_hostname: "{{ ansible_default_ipv4.address }}"
chronos_framework_name: "chronos"
chronos_port: '4400'
chronos_https_port: '4443'
chronos_keystore_path: '/etc/chronos/ssl_keystore.jks'
chronos_server_zk_group: chronos_servers
chronos_image: "indigodatacloud/chronos:{{ chronos_version }}"
chronos_master_peers: "zk://{{ zookeeper_peers_nodes }}/mesos"
chronos_zk_peers: "zk://{{ zookeeper_peers_nodes }}"

chronos_ssl_ks_password: "
   {%- if generate_random_pass|string() == 'true' -%}
	    {{ chronos_jks_randpassword.stdout  }}
   {%- else -%}
            {{ chronos_jks_password }}
   {%- endif -%}
"


