---

# Zookeeper variable
zookeeper_client_port: "2181"
zookeeper_server_group: zookeeper_servers

zookeeper_peers_nodes: "
	{%- if zookeeper_peers is defined -%}
            {% for host in zookeeper_peers %}{{host}}:{{zookeeper_client_port}}{% if not loop.last %},{% endif %}{% endfor %}
	{%- else -%}
	    {%- set zookeeper_peers = [] -%}
	    {%- for host in groups[zookeeper_server_group] -%}
	      {%- if host not in zookeeper_peers -%}
	        {%- set current_host = hostvars[host]['ansible_eth0']['ipv4']['address'] + ':' + zookeeper_client_port -%}
	        {%- do zookeeper_peers.append(current_host) -%}
	      {%- endif -%}
	    {%- endfor -%}
	    {{ zookeeper_peers|join(',') }}
	{%- endif -%}
"

# defaults file for marathon
marathon_version: 'latest'
marathon_hostname: "{{ ansible_default_ipv4.address }}"
marathon_framework_name: "marathon"
marathon_port: '8080'
marathon_server_zk_group: marathon_servers
marathon_image: "indigodatacloud/marathon:{{ marathon_version }}"
marathon_master_peers: "zk://{{ zookeeper_peers_nodes }}/mesos"
marathon_zk_peers: "zk://{{ zookeeper_peers_nodes }}"

# Note: marathon-consul checks the certificate CN against the host marathon.service.consul
openssl_self_signed:
# - { name : "{{ ansible_default_ipv4.address }}" }
 - { name : "marathon.service.consul" }
generate_random_pass: "true"
marathon_key_password: "password"
marathon_pkcs_password: "password"
marathon_jks_password: "password"
marathon_username: "admin"
marathon_password: "secr3t"
marathon_https_port: '8443'
marathon_keystore_path: '/etc/marathon/ssl_keystore.jks'

marathon_ssl_ks_password: "
   {%- if generate_random_pass|string() == 'true' -%}
            {{ marathon_jks_randpassword.stdout  }}
   {%- else -%}
            {{ marathon_jks_password }}
   {%- endif -%}
"

marathon_consul_version: 'latest'
marathon_consul_image: "ciscocloud/marathon-consul:{{marathon_consul_version}}"

marathon_consul_app_json: '{
  "id": "marathon-consul",
  "args": ["--registry=http://consul.service.consul:8500 --marathon-protocol=https --marathon-username={{marathon_username}} --marathon-password={{marathon_password}} --marathon-location=marathon.service.consul:{{marathon_https_port}}"],
  "container": {
    "type": "DOCKER",
    "docker": {
      "image": "{{marathon_consul_image}}",
      "network": "BRIDGE",
      "portMappings": [{"containerPort": 4000, "hostPort": 0, "protocol": "tcp"}]
    },
    "volumes": [
      {
        "containerPath": "/usr/local/share/ca-certificates",
        "hostPath": "/usr/local/share/ca-certificates/",
        "mode": "RO"
      },
     ]
  },
  "instances": 1,
  "cpus": 0.1,
  "mem": 128
}'

mesos_consul_app_json: '{
  "args": [
    "--zk=zk://zookeeper.service.consul:2181/mesos",
    "--mesos-ip-order=mesos,host"
  ],
  "container": {
    "type": "DOCKER",
    "docker": {
      "network": "BRIDGE",
      "image": "ciscocloud/mesos-consul"
    }
  },
  "id": "mesos-consul",
  "instances": 1,
  "cpus": 0.1,
  "mem": 256
}' 
