---
# defaults file for marathon
marathon_version: 'latest'
#marathon_hostname: "{{ ansible_hostname }}"
marathon_hostname: "{{ ansible_default_ipv4.address }}"
marathon_framework_name: "marathon"
marathon_port: '8080'
marathon_server_zk_group: marathon_servers
marathon_image: "indigodatacloud/marathon:{{ marathon_version }}"
marathon_master_peers: "zk://{{ zookeeper_peers_nodes }}/mesos"
marathon_zk_peers: "zk://{{ zookeeper_peers_nodes }}"
marathon_consul_version: 'latest'
marathon_consul_image: "ciscocloud/marathon-consul:{{marathon_consul_version}}"

marathon_consul_app_json: '{
  "id": "marathon-consul",
  "args": ["--registry=http://consul.service.consul:8500 --marathon-location=marathon.service.consul:8080"],
  "container": {
    "type": "DOCKER",
    "docker": {
      "image": "{{marathon_consul_image}}",
      "network": "BRIDGE",
      "portMappings": [{"containerPort": 4000, "hostPort": 0, "protocol": "tcp"}]
    }
  },
  "instances": 1,
  "cpus": 0.1,
  "mem": 128
}'

mesos_consul_app_json: '{
  "args": [
    "--zk=zk://zookeeper.service.consul:2181/mesos",
    "--mesos-ip-order=mesos,host"
  ],
  "container": {
    "type": "DOCKER",
    "docker": {
      "network": "BRIDGE",
      "image": "ciscocloud/mesos-consul"
    }
  },
  "id": "mesos-consul",
  "instances": 1,
  "cpus": 0.1,
  "mem": 256
}' 
