- wait_for: port="{{marathon_https_port}}" host=marathon.service.consul delay=6 timeout=60 

- name: start mesos-consul app
  run_once: true
  uri:
     url: "https://marathon.service.consul:{{marathon_https_port}}/v2/apps/mesos-consul"
     user: "{{marathon_username}}"
     password: "{{marathon_password}}"
     validate_certs: "no"
     method: PUT
     HEADER_Content-Type: "application/json"
     body: "{{mesos_consul_app_json}}"
     body_format: json
  register: result
  until: result.status == 200
  retries: 3
  delay: 10
  changed_when: false
  tags:
    - marathon


- name: start marathon-consul app
  run_once: true
  uri: 
     url: "https://marathon.service.consul:{{marathon_https_port}}/v2/apps/marathon-consul"
     user: "{{marathon_username}}"
     password: "{{marathon_password}}"
     validate_certs: "no"
     method: PUT
     HEADER_Content-Type: "application/json"
     body: "{{marathon_consul_app_json}}"
     body_format: json
  register: result
  until: result.status == 200
  retries: 3
  delay: 10
  changed_when: false
  tags:
    - marathon


