- name: start mesos-consul app
  run_once: true
  uri:
     url: "http://marathon.service.consul:8080/v2/apps/mesos-consul"
     method: PUT
     HEADER_Content-Type: "application/json"
     body: "{{mesos_consul_app_json}}"
     body_format: json
  register: result
  until: result.status == 200
  retries: 3
  delay: 10
  changed_when: false
  tags:
    - marathon


- name: start marathon-consul app
  run_once: true
  uri: 
     url: "http://marathon.service.consul:8080/v2/apps/marathon-consul"
     method: PUT
     HEADER_Content-Type: "application/json"
     body: "{{marathon_consul_app_json}}"
     body_format: json
  register: result
  until: result.status == 200
  retries: 3
  delay: 10
  changed_when: false
  tags:
    - marathon


