- name: run marathon container
  docker:
    name: marathon
    image: "{{ marathon_image }}"
    state: started
    detach: true
    restart_policy: always
    net: host
    env:
      MARATHON_HOSTNAME: "{{ marathon_hostname }}" 
      MARATHON_HTTP_ADDRESS: "{{ marathon_hostname }}" 
      MARATHON_MASTER: "{{ marathon_master_peers }}"
      MARATHON_ZK: "{{ marathon_zk_peers }}/{{ marathon_framework_name }}" 
      MARATHON_FRAMEWORK_NAME: "{{ marathon_framework_name }}"
