- name: generate marathon key password
  shell: head /dev/urandom | tr -dc A-Za-z0-9 | head -c10
  register: marathon_key_randpassword
  when: generate_random_pass == "true"

- name: generate marathon jks password
  shell: head /dev/urandom | tr -dc A-Za-z0-9 | head -c10
  register: marathon_jks_randpassword
  when: generate_random_pass == "true"

- name: Install openjdk
  apt: name="openjdk-7-jre-headless" state=present


- name: generate keystore with random password
  vars: 
    key_password: "{{marathon_key_randpassword.stdout}}"
    pkcs_password: "{{marathon_jks_randpassword.stdout}}"
    jks_password: "{{marathon_jks_randpassword.stdout}}"
  include: enable_ssl.yml
  when: generate_random_pass == "true"


- name: generate keystore
  vars:
    key_password: "{{marathon_key_password}}"
    pkcs_password: "{{marathon_jks_password}}"
    jks_password: "{{marathon_jks_password}}"
  include: enable_ssl.yml
  when: generate_random_pass != "true"


- name: run marathon container
  docker:
    name: marathon
    image: "{{ marathon_image }}"
    state: started
    detach: true
    restart_policy: always
    net: host
    volumes:
    - "{{ marathon_keystore_path }}:{{ marathon_keystore_path }}"
    env:
      MARATHON_HOSTNAME: "{{ marathon_hostname }}" 
      MARATHON_HTTP_ADDRESS: "{{ marathon_hostname }}" 
      MARATHON_HTTPS_ADDRESS: "{{ marathon_hostname }}"
      MARATHON_MASTER: "{{ marathon_master_peers }}"
      MARATHON_ZK: "{{ marathon_zk_peers }}/{{ marathon_framework_name }}" 
      MARATHON_FRAMEWORK_NAME: "{{ marathon_framework_name }}"
      MARATHON_HTTPS_PORT: "{{ marathon_https_port }}"
      MARATHON_SSL_KEYSTORE_PASSWORD: "{{ marathon_ssl_ks_password }}"
      MARATHON_SSL_KEYSTORE_PATH: "{{ marathon_keystore_path }}"
      MARATHON_HTTP_CREDENTIALS: "{{marathon_username}}:{{marathon_password}}"
  tags: marathon

- name: register marathon service with curl check
  consul:
    service_name: marathon
    service_port: "{{marathon_https_port}}"
    script: "curl -k -u {{marathon_username}}:{{marathon_password}} https://{{marathon_hostname}}:{{marathon_https_port}}"
    interval: 10s
    tags: marathon

- include: apps.yml
