- name: run marathon container
  docker:
    name: marathon
    image: "{{ marathon_image }}"
    state: started
    detach: true
    restart_policy: always
    net: host
    env:
      MARATHON_HOSTNAME: "{{ marathon_hostname }}" 
      MARATHON_HTTP_ADDRESS: "{{ marathon_hostname }}" 
      MARATHON_MASTER: "{{ marathon_master_peers }}"
      MARATHON_ZK: "{{ marathon_zk_peers }}/{{ marathon_framework_name }}" 
      MARATHON_FRAMEWORK_NAME: "{{ marathon_framework_name }}"
  tags: marathon

- name: register marathon service with curl check
  consul:
    service_name: marathon
    service_port: 8080
    script: "curl http://{{marathon_hostname}}:8080"
    interval: 10s
    tags: marathon

- include: apps.yml
